"""Single Source of Truth für die Roadmap-Swimlane-Grafik (AP-68).
Bei jeder neuen AP hier eine Zeile ergänzen (Thema/Datum/Status) — analog zur
Prosa-Liste in docs/projekt/roadmap.md. Reine Daten, kein Import.

Kuratiert aus mermaid-sources/projekt-roadmap-1.mmd (Datum + Status) und
mermaid-sources/entwicklung-arbeitspakete-1.mmd (Thema via subgraph C1–C10),
siehe tools/_bootstrap_roadmap_data.py. Mehrteilige APs (z. B. AP-31/AP-34, die
sowohl einen erledigten Kern als auch einen offenen Rest im Gantt tragen)
erscheinen genau einmal — mit status="open" und dem Zieldatum des offenen
Rests, da die AP als Ganzes noch nicht abgeschlossen ist.
"""

THEMES = [
    ("engine",     "⚙️ Engine / Fundament"),
    ("backends",   "🔌 Verbindungen & Backends"),
    ("sqlbuilder", "🧩 SQL-Builder & SQL-Ausgabe"),
    ("graphviz",   "🕸️ Graph-Visualisierung"),
    ("datenui",    "🗂️ Daten & UI-Rahmen"),
    ("betrieb",    "🚀 Deployment & Betrieb"),
    ("doku",       "📚 Doku & Prozess"),
    ("migration",  "🧬 Legacy-DB-Migration / Export"),
    ("objekte",    "🗃️ DB-Objekt-Kategorien"),
    ("verbux",     "🔧 Verbindungs-UX & Demo-Daten"),
]

# Aus _bootstrap_roadmap_data.py kuratiert. Labels gekürzt (passen ins Diagramm).
APS = [
    {"ap": "AP-1", "label": "Graph-Interaktion (UML)", "theme": "graphviz", "date": "2026-06-25", "status": "done"},
    {"ap": "AP-2", "label": "Fix Verbinden-Fehler", "theme": "backends", "date": "2026-06-25", "status": "done"},
    {"ap": "AP-3", "label": "SQL-Optionen-Paket", "theme": "sqlbuilder", "date": "2026-06-25", "status": "done"},
    {"ap": "AP-4", "label": "Mehrere SELECT-Spalten", "theme": "sqlbuilder", "date": "2026-06-25", "status": "done"},
    {"ap": "AP-5", "label": "Ausgabebereich (SELECT)", "theme": "sqlbuilder", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-6", "label": "Ausgabe-Steuerung", "theme": "sqlbuilder", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-7", "label": "Feiner Graph-Zoom", "theme": "graphviz", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-8", "label": "Fix Auswahl-Reset", "theme": "graphviz", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-9", "label": "Ergebnisliste maximiert", "theme": "sqlbuilder", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-14", "label": "Py3.14 Win+Linux/AppImage", "theme": "betrieb", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-11", "label": "Composite FK voll", "theme": "engine", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-10", "label": "Verbindungen in Topbar", "theme": "backends", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-13", "label": "UI-Politur", "theme": "graphviz", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-15", "label": "abbruchsicher (Win+Linux)", "theme": "betrieb", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-12", "label": "MSSQL Treiber+Test", "theme": "backends", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-20", "label": "Copy-Icon am SELECT", "theme": "sqlbuilder", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-21", "label": "Kosmetik Balkenhöhe", "theme": "graphviz", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-23", "label": "Join-Maske vereinheitlicht", "theme": "sqlbuilder", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-16", "label": "Graph entzerren (dagre)", "theme": "graphviz", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-18", "label": "Multi-Tabellen-Join", "theme": "datenui", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-28", "label": "Scroll nur im Ergebnis", "theme": "graphviz", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-32", "label": "Zoom-Slider Kopfzeile", "theme": "graphviz", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-26", "label": "Audit-Sessions", "theme": "doku", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-27", "label": "Insights-Prozess", "theme": "doku", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-33", "label": "Logging sauber", "theme": "betrieb", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-29", "label": "SQL-Dialekt umschalten", "theme": "sqlbuilder", "date": "2026-06-26", "status": "done"},
    {"ap": "AP-30", "label": "N-1-Stern Auto-Weaving", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-25", "label": "SQL-Statement-Analyzer", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-36", "label": "Fan-out-Richtung pro Join", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-37", "label": "Start⇄Ziel-Tausch", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-38", "label": "Kopierbares SQL", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-39", "label": "SQL-Analyzer vertieft", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-40", "label": "Graph-Legende+Marker-Fix", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-41", "label": "Join-Typ pro Schritt", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-42", "label": "SQL-Builder-Politur", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-43", "label": "Mehrzeiliges SQL-Layout", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-44", "label": "Kompakter + NULL/Status", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-46", "label": "Detailkarten folgen Auswahl", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-47", "label": "Pfad-Indikator+Waisen-Chip", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-48", "label": "Analyzer-Textbox+Lint", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-49", "label": "Analyzer-Feinschliff", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-45", "label": "Spaltenkopf-Aktionen", "theme": "sqlbuilder", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-50", "label": "Unique → 1-1-Klassifikation", "theme": "engine", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-51", "label": "Unique-Index Uniqueness", "theme": "engine", "date": "2026-06-27", "status": "done"},
    {"ap": "AP-52", "label": "Multi-Schema-Reflection", "theme": "backends", "date": "2026-06-28", "status": "done"},
    {"ap": "AP-53", "label": "Oracle-Verbindung", "theme": "backends", "date": "2026-06-28", "status": "done"},
    {"ap": "AP-A", "label": "Umbenennung SQL-Builder", "theme": "sqlbuilder", "date": "2026-06-28", "status": "done"},
    {"ap": "AP-B", "label": "Klausel-Sektionen", "theme": "sqlbuilder", "date": "2026-06-28", "status": "done"},
    {"ap": "AP-C+D", "label": "Join-Typ inline + 1-N", "theme": "sqlbuilder", "date": "2026-06-28", "status": "done"},
    {"ap": "AP-E", "label": "Zeilen Move ↑/↓", "theme": "sqlbuilder", "date": "2026-06-28", "status": "done"},
    {"ap": "AP-F", "label": "Analyzer-Vorschläge", "theme": "sqlbuilder", "date": "2026-06-28", "status": "done"},
    {"ap": "AP-58", "label": "Fix HAVING-Layout", "theme": "sqlbuilder", "date": "2026-06-28", "status": "done"},
    {"ap": "AP-59", "label": "2-Spalten-Raster", "theme": "sqlbuilder", "date": "2026-06-28", "status": "done"},
    {"ap": "AP-60", "label": "Connection-Form-Ausrichtung", "theme": "verbux", "date": "2026-06-28", "status": "done"},
    {"ap": "AP-54", "label": "Cross-Schema-FK-Diagnose", "theme": "migration", "date": "2026-06-28", "status": "done"},
    {"ap": "AP-55", "label": "Implied-FK-Schärfung", "theme": "migration", "date": "2026-06-28", "status": "done"},
    {"ap": "AP-56a", "label": "Subset-Footprint", "theme": "migration", "date": "2026-06-28", "status": "done"},
    {"ap": "AP-64", "label": "Verbindungsform-Umbau", "theme": "verbux", "date": "2026-06-29", "status": "done"},
    {"ap": "AP-56b·1", "label": "Subset-Live-Zeilenzahlen", "theme": "migration", "date": "2026-06-29", "status": "done"},
    {"ap": "AP-56b·2", "label": "Subset-Daten-Dump (JSON)", "theme": "migration", "date": "2026-06-29", "status": "done"},
    {"ap": "AP-56c", "label": "Subset-IN-Listen", "theme": "migration", "date": "2026-06-29", "status": "done"},
    {"ap": "AP-63·S1", "label": "Indizes+Check-Constraints", "theme": "objekte", "date": "2026-06-29", "status": "done"},
    {"ap": "AP-63·S2", "label": "Trigger-Sidebar-Kategorie", "theme": "objekte", "date": "2026-06-29", "status": "done"},
    {"ap": "AP-63·S2b", "label": "Sequences+Mat-Views", "theme": "objekte", "date": "2026-06-29", "status": "done"},
    {"ap": "AP-63·S3", "label": "Procedures/Functions/Pkg", "theme": "objekte", "date": "2026-06-29", "status": "done"},
    {"ap": "AP-63·Trigger-FF", "label": "PG/Oracle/MSSQL-Trigger", "theme": "objekte", "date": "2026-06-29", "status": "done"},
    {"ap": "AP-66·S1", "label": "View→Routinen-Abhängigk.", "theme": "objekte", "date": "2026-06-29", "status": "done"},
    {"ap": "AP-65·A", "label": "Analyzer Parse-Fehler-Pos.", "theme": "sqlbuilder", "date": "2026-06-29", "status": "done"},
    {"ap": "AP-65·A-Härtung", "label": "Unclosed-Quote-Pos+Hint", "theme": "sqlbuilder", "date": "2026-06-30", "status": "done"},
    {"ap": "AP-67·MSSQL-Grundlage", "label": "Synonyme+Server-Demo", "theme": "objekte", "date": "2026-06-30", "status": "done"},
    {"ap": "AP-65·A-Härtung 2", "label": "Unclosed-Quote echte Zeile", "theme": "sqlbuilder", "date": "2026-07-01", "status": "done"},
    {"ap": "AP-65·B", "label": "Zeilennummern-Gutter", "theme": "sqlbuilder", "date": "2026-07-01", "status": "done"},
    {"ap": "AP-65·C", "label": "Lints mit Zeilenbezug", "theme": "sqlbuilder", "date": "2026-07-01", "status": "done"},
    {"ap": "AP-67·Oracle-Adaption", "label": "Oracle-Demo-CMDB", "theme": "objekte", "date": "2026-07-01", "status": "done"},
    {"ap": "AP-67 Slice 2a", "label": "reiches Oracle-Schema", "theme": "objekte", "date": "2026-07-01", "status": "done"},
    {"ap": "AP-68", "label": "Roadmap-Swimlane", "theme": "doku", "date": "2026-07-01", "status": "done"},
    {"ap": "AP-69·A", "label": "SQL-Editor-Komponente", "theme": "sqlbuilder", "date": "2026-07-01", "status": "done"},
    # … alle erledigten APs (status="done") oben + offene (status="open") unten …
    {"ap": "AP-35", "label": "run.ps1 leeres-venv-Fix", "theme": "betrieb", "date": "2026-06-28", "status": "open"},
    {"ap": "AP-31", "label": "Idle-Shutdown/Deploy (Rest)", "theme": "betrieb", "date": "2026-06-29", "status": "open"},
    {"ap": "AP-34", "label": "Log-Fenster/Verknüpfung", "theme": "betrieb", "date": "2026-06-29", "status": "open"},
    {"ap": "AP-19", "label": ".pattern_transfer", "theme": "doku", "date": "2026-06-30", "status": "open"},
    {"ap": "AP-57", "label": "Cross-Schema-Joins", "theme": "migration", "date": "2026-07-04", "status": "open"},
    {"ap": "AP-66·S2/S3", "label": "Views→Routinen (Rest)", "theme": "objekte", "date": "2026-07-10", "status": "open"},
    {"ap": "AP-61", "label": "Demo-CMDB → volle CMDB", "theme": "verbux", "date": "2026-07-11", "status": "open"},
    {"ap": "AP-62", "label": "Passwort-Keyring", "theme": "verbux", "date": "2026-07-12", "status": "open"},
]
